//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartUpWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class DocumentOfStartUp
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public byte[] Blob { get; set; }
        public int StartUpId { get; set; }
        public bool IsPublic { get; set; }
    
        public virtual StartUp StartUp { get; set; }
    }
}
