//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartUpWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class DocumentOfStartUp
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public byte[] Blob { get; set; }
        public int StartUpId { get; set; }
        public bool IsPublic { get; set; }
    
        public virtual StartUp StartUp { get; set; }
    }
}
