//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartUpWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    [System.Serializable] public partial class StartUpOfTeam
    {
        public int TeamId { get; set; }
        public int RoleTypeId { get; set; }
        public int StartUpId { get; set; }
    
        public virtual RoleType RoleType { get; set; }
        public virtual StartUp StartUp { get; set; }
        public virtual Team Team { get; set; }
    }
}
