//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartUpWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class TeamComment
    {
        public int UserId { get; set; }
        public int TeamId { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Id { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
