//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartUpWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    [System.Serializable] public partial class TeamComment
    {
        public int UserId { get; set; }
        public int TeamId { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Id { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
